/* 
 * madana-api
 *
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.MadanaSampleclient.Api;
using Com.MadanaSampleclient.Model;
using Com.MadanaSampleclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.MadanaSampleclient.Test
{
    /// <summary>
    ///  Class for testing JsonAnalysisRequestAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonAnalysisRequestActionTests
    {
        // TODO uncomment below to declare an instance variable for JsonAnalysisRequestAction
        //private JsonAnalysisRequestAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JsonAnalysisRequestAction
            //instance = new JsonAnalysisRequestAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JsonAnalysisRequestAction
        /// </summary>
        [Test]
        public void JsonAnalysisRequestActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" JsonAnalysisRequestAction
            //Assert.IsInstanceOf(typeof(JsonAnalysisRequestAction), instance);
        }


        /// <summary>
        /// Test the property 'RequestID'
        /// </summary>
        [Test]
        public void RequestIDTest()
        {
            // TODO unit test for the property 'RequestID'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Connection'
        /// </summary>
        [Test]
        public void ConnectionTest()
        {
            // TODO unit test for the property 'Connection'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Fingerprint'
        /// </summary>
        [Test]
        public void FingerprintTest()
        {
            // TODO unit test for the property 'Fingerprint'
        }
        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Test]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

    }

}
