/* 
 * madana-api
 *
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.MadanaSampleclient.Api;
using Com.MadanaSampleclient.Model;
using Com.MadanaSampleclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.MadanaSampleclient.Test
{
    /// <summary>
    ///  Class for testing JsonMDNUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonMDNUserTests
    {
        // TODO uncomment below to declare an instance variable for JsonMDNUser
        //private JsonMDNUser instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JsonMDNUser
            //instance = new JsonMDNUser();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JsonMDNUser
        /// </summary>
        [Test]
        public void JsonMDNUserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" JsonMDNUser
            //Assert.IsInstanceOf(typeof(JsonMDNUser), instance);
        }


        /// <summary>
        /// Test the property 'Mail'
        /// </summary>
        [Test]
        public void MailTest()
        {
            // TODO unit test for the property 'Mail'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Test]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Test]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
        /// <summary>
        /// Test the property 'SocialAccounts'
        /// </summary>
        [Test]
        public void SocialAccountsTest()
        {
            // TODO unit test for the property 'SocialAccounts'
        }
        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Test]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

    }

}
