/* 
 * madana-api
 *
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Com.MadanaSampleclient.Client;
using Com.MadanaSampleclient.Api;
using Com.MadanaSampleclient.Model;

namespace Com.MadanaSampleclient.Test
{
    /// <summary>
    ///  Class for testing UserServiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UserServiceApiTests
    {
        private UserServiceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserServiceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserServiceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' UserServiceApi
            //Assert.IsInstanceOf(typeof(UserServiceApi), instance);
        }

        
        /// <summary>
        /// Test CreateObject2
        /// </summary>
        [Test]
        public void CreateObject2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string referrer = null;
            //JsonMDNUser body = null;
            //var response = instance.CreateObject2(referrer, body);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test DeleteObject
        /// </summary>
        [Test]
        public void DeleteObjectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.DeleteObject(username);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test DeleteObject_0
        /// </summary>
        [Test]
        public void DeleteObject_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ident = null;
            //string platform = null;
            //string username = null;
            //var response = instance.DeleteObject_0(ident, platform, username);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetAvatars
        /// </summary>
        [Test]
        public void GetAvatarsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.GetAvatars(username);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetCertificates
        /// </summary>
        [Test]
        public void GetCertificatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.GetCertificates(username);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetObject2
        /// </summary>
        [Test]
        public void GetObject2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //var response = instance.GetObject2(username);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test SetAvatar
        /// </summary>
        [Test]
        public void SetAvatarTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //JsonMDNUserProfileImage body = null;
            //var response = instance.SetAvatar(username, body);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test SetSettings
        /// </summary>
        [Test]
        public void SetSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //JsonMDNUserSetting body = null;
            //var response = instance.SetSettings(username, body);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test UpdateObject2
        /// </summary>
        [Test]
        public void UpdateObject2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string username = null;
            //JsonMDNUser body = null;
            //var response = instance.UpdateObject2(username, body);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
    }

}
